### ISSUE TITLE
How to mock daos from jooq

### ISSUE THREAD

**Issue by RikuVan** [webDevAndSausages/world-of-webdevandsausages#10]
Now that the code has been refactored it presents a new problem because we are using the daos directly in the controllers. To test the controllers we need to mock the daos. This was easy before when they were behind an extra layer. But I can't see how to mock the daos. Now the controller tests ar e broken when the database is not open.

**Comment by RikuVan** [comment]
well I put these daos behind repository objects so the mocking works now. I would rather have ease of testing over the dumbness of having this extra layer. But if someone can figure out a better solution, lets remove them.

**Comment by leomelin** [comment]
I think this is resolved now
