### ISSUE TITLE
Event editing CLI

### ISSUE THREAD

**Issue by RikuVan** [webDevAndSausages/world-of-webdevandsausages#3]
CLI to add/edit events on the server:

should be able to:
- create event
- update, e.g. status, dates, etc
- update/ delete participants to e.g. change their places in line

**Comment by RikuVan** [comment]
ok lets do it this way:

`/admin` routes in the main app which is not routed to with nginx
then a simple cli, maybe node, allowing us to use the admin routes by just ssh-ing into the server

**Comment by leomelin** [comment]
Also we could do a cli that runs in a local docker container that opens ssh tunnel so we don't need to manually ssh to the server. Also the whole cli that utilizes /admin routes could be done with ansible roles I think https://docs.ansible.com/ansible/latest/user_guide/playbooks_prompts.html

**Comment by RikuVan** [comment]
I will start adding the admin endpoints

**Comment by leomelin** [comment]
This is now split to separate issues and partly done
