### ISSUE TITLE
Registration cancellation

### ISSUE THREAD

**Issue by RikuVan** [webDevAndSausages/world-of-webdevandsausages#4]
DELETE /api/1.0/event/{id}/registrations/{token}

In addition to removing a participant, cancellation should also:

- send verification of cancellation email to user
- check if user was in full event and change status to registered of next participant in waiting list, also resulting dispatching of email to sendgrid to inform lucky participant

**Comment by leomelin** [comment]
I can take this one

**Comment by RikuVan** [comment]
the sendgrid cancellation email template id: d-831c9bf56bcf4401893121910f177f0a
needed in the sendgrid config

**Comment by RikuVan** [comment]
and the template id for upgrades from waiting list to registered: d-f7fd0df79d1e49d39e177d599b0411e7

**Comment by RikuVan** [comment]
the upgrade template should include these values to interpolate: sponsor, location, datetime, token

**Comment by leomelin** [comment]
This is now done
