### ISSUE TITLE
New frontend design

### ISSUE THREAD

**Issue by RikuVan** [webDevAndSausages/world-of-webdevandsausages#50]
While I did spend some time porting the Preact stuff to fresh React in typescript and adding the, what I think is cool console forms, the site really needs a make-over. 1. We need a real designer to offer a concept. 2. We might consider to porting to Gatsby which would probably improve seo, and offer a lot of easy-to-use plugins for loading and optimizing static content. This might be a good summer project for me :)

**Comment by RikuVan** [comment]
We might consider putting what we have in Gatsby which should be easy to enough to do. That would give us access to Gatsby's rich plugins and better seo. Or maybe Svelte for even more churn :)

**Comment by RikuVan** [comment]
Tuomo has started working on a new design. Yeah!
An initial idea...
![wds](https://user-images.githubusercontent.com/7317771/57567782-1183ca00-73e7-11e9-8742-e3c39c1b4823.png)

**Comment by leomelin** [comment]
Awesome!
Just a couple of thoughts:
I think the initial idea looks cool and fresh and really professional there's no sausages feel in the logo. I think there should be some. Also: Do you think completely changing the logo is a good idea as it'll make all our swag outdated and not usable?

**Comment by RikuVan** [comment]
I think there is a sausage coming somewhere! But our old swag is just vintage...well anyways we don't have lots of old stuff anyways except a few stickers. I would expect the brand/concept to evolve over time.

**Comment by leomelin** [comment]
Yep, no strong feelings against the brand change, just wanted to share my thoughs as something to consider

**Comment by RikuVan** [comment]
![wds-tron-sausage](https://user-images.githubusercontent.com/7317771/57581470-68a99d80-74c0-11e9-8be7-fb4455b21edb.png)
![wds-tron-sausage-2](https://user-images.githubusercontent.com/7317771/57581471-6a736100-74c0-11e9-93af-5d6ec8df172e.png)

**Comment by RikuVan** [comment]
think I prefer more abstract myself

**Comment by RikuVan** [comment]
![wds-grill](https://user-images.githubusercontent.com/7317771/57581737-706b4100-74c4-11e9-9680-caf88083b196.png)

**Comment by RikuVan** [comment]
That is the best in my opinion. What do you think Leo?

**Comment by jkumara** [comment]
The style overall looks really good. This spatula looks best so far to me. Although I don't know if it's a little ambiguous at a first glance, took at least a little time for me to realize that it's a spatula. The sausage (and the fork in the current logo) are nice in that way that they are instantly recognizable.

**Comment by RikuVan** [comment]
![wds-penis-grill](https://user-images.githubusercontent.com/7317771/59110360-9e1e9b00-8947-11e9-9e99-b3b02c58fcab.png)

**Comment by RikuVan** [comment]
^@leomelin @jkumara the latest iteration by tuomo.

**Comment by leomelin** [comment]
Wow, I think that's pretty cool!

**Comment by RikuVan** [comment]
will close this since first new frontend is being tested and make new issue for fixes
