### ISSUE TITLE
Site broken on Edge

### ISSUE THREAD

**Issue by leomelin** [webDevAndSausages/world-of-webdevandsausages#71]
On edge the site doesn't load properly. Shows error message:
500
Cannot convert null or undefined to object

**Comment by RikuVan** [comment]
I think this is an older version of Edge that did not support the spread syntax. I have added a babel polyfill to the Sapper build. Someone needs to verify that this does the job.

**Comment by RikuVan** [comment]
Checked on browserstack and this bug is gone in Chromium Edge but still exists in Edge 18...dunno if it is worth trying to fix further. Opinions?

**Comment by RikuVan** [comment]
ok, now I got it working all the way back to Edge 16, which I think is fine. Will never work on IE11 since we have css vars all over the place.

**Comment by leomelin** [comment]
If someone interested in WD&S uses IE11, he/she doesn't deserve our company
