### ISSUE TITLE
Feature request: Export the event to google calendar or .ics

### ISSUE THREAD

**Issue by onnimonni** [webDevAndSausages/world-of-webdevandsausages#74]
Hey!

It would be awesome to be able to add the event into my personal calendar with one click after the registration.

I don't want to miss the event and this helps users to keep track of their registrations.

Thanks 🍻!

**Comment by RikuVan** [comment]
I think I will first add a save the date button to the event terminal to download the ics file since not all users get/use the email. But would be nice to have in the email as well.

**Comment by RikuVan** [comment]
This addition is now in a PR: https://github.com/webDevAndSausages/world-of-webdevandsausages/pull/80
